# Generated by Django 4.2.6 on 2023-11-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_producto_categoria_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('xbox 360', 'Xbox 360'), ('xbox one', 'Xbox One'), ('xbox x', 'Xbox X'), ('ps3', 'PS3'), ('ps4', 'PS4'), ('ps5', 'PS5')], default='xbox', max_length=20),
        ),
    ]
