# Generated by Django 4.2.6 on 2023-11-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Xbox 360', 'Xbox 360'), ('Xbox One', 'Xbox One'), ('Xbox X', 'Xbox X'), ('PS3', 'PS3'), ('PS4', 'PS4'), ('PS5', 'PS5')], default='xbox', max_length=20),
        ),
    ]
