# Generated by Django 4.2.6 on 2023-11-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0005_carritoitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarritoItem',
        ),
    ]
